// <auto-generated />
namespace CarRental.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class carpriceoffseason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(carpriceoffseason));
        
        string IMigrationMetadata.Id
        {
            get { return "201606120427534_car-price-off-season"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
